# Streamlit Theme Configuration

[theme]

# "light"テーマをベースにする
base = "light"

# 主要なウィジェットの色を、落ち着いた青色に設定します
primaryColor = "#0d6efd"

# 全体の背景色を、純粋な白ではなく、少しだけグレーがかった色にします
backgroundColor = "#f0f2f6"

# サイドバーやコンテナの背景色を、メインの背景より少し明るい色にします
secondaryBackgroundColor = "#ffffff"

# テキストの色を、真っ黒ではなく、少し柔らかいダークグレーにします
textColor = "#1e293b"

# フォントをゴシック体系（sans-serif）に設定します
font = "sans serif"


[app]
title = "Universal AIマッチング"
version = "1.0.0"  #

[email_processing]
fetch_limit = 100

[llm]
model_name = "models/gemini-2.5-pro"


[messages]
# 営業スタッフ向けの重要メッセージ。空の場合は表示されません。
# HTMLタグを使用して、色やスタイルをカスタマイズできます。
sales_staff_notice = """
<div style="background-color: #ffcccc; color: #cc0000; padding: 10px; border-radius: 5px; border: 2px solid #cc0000; font-weight: bold; text-align: center; margin-bottom: 20px;">
    🚨 営業スタッフへ: メール読み込み後、担当者、技術者管理より、担当をアサインしてください。<br>
    マッチング不要な案件、技術者はアーカイブするようにしてください。マッチング処理から除外されます。<br>
    特にS, A, B評価の技術者は優先的にアプローチしましょう！
</div>
"""
# 上のメッセージを非表示にする場合は、以下の行をコメントアウトするか空にしてください。
# sales_staff_notice = ""

showSidebarNavigation = false


# ▼▼▼【ここから追加】▼▼▼
[options]
# 進捗ステータスの選択肢リスト
# この順番でUIに表示されます
status = [
    "新規",
    "提案準備中",
    "提案中",
    "クライアント面談",
    "結果待ち",
    "採用",
    "見送り（自社都合）",
    "見送り（クライアント都合）",
    "見送り（技術者都合）",
    "クローズ"
]

